# Generated by Django 4.1.5 on 2023-09-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='ask',
            new_name='question',
        ),
    ]
